#!/usr/bin/env python3
"""Bundle local ModuleScripts for the legacy single-file HTTP loader.

Studio uses ui/ directly. No network access or third-party Python packages needed.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = [
    'Theme', 'Icons', 'ComponentBuilder', 'TabManager',
    'vendor/Obsidian', 'vendor/ThemeManager', 'vendor/SaveManager', 'MatchaUI',
]


def bundle():
    license_text = (ROOT / 'ui/vendor/LICENSE').read_text()
    license_text += '\n' + (ROOT / 'ui/vendor/LICENSE-Lucide').read_text()
    license_text += '\n' + (ROOT / 'ui/vendor/LICENSE-Lucide-Icons').read_text()
    output = ['-- GENERATED by tools/build_ui.py; edit ui/ instead.\n',
              '--[[\n' + license_text + '\n]]\n',
              'local factories, cache = {}, {}\n',
              'local function import(name)\n',
              '    if cache[name] == nil then cache[name] = factories[name]() end\n',
              '    return cache[name]\nend\n']
    for name in MODULES:
        source = (ROOT / 'ui' / (name + '.lua')).read_text()

        def replace_require(match):
            parts = name.split('/')
            for part in match[1].split('.')[1:]:
                if part == 'Parent':
                    parts.pop()
                else:
                    parts.append(part)
            target = '/'.join(parts)
            if target not in MODULES:
                raise ValueError(f'{name}: unknown module {target}')
            return f'import("{target}")'

        source = re.sub(r'require\((script(?:\.[A-Za-z_][A-Za-z_0-9]*)+)\)',
                        replace_require, source)
        output.append(f'\n-- Module: {name}\nfactories["{name}"] = function()\n{source}\nend\n')
    output.append('\nreturn import("MatchaUI")\n')
    return ''.join(output)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'dist/MatchaUI.lua'
    result = bundle()
    if args.check:
        if not path.exists() or path.read_text() != result:
            raise SystemExit('UI bundle is stale; run python3 tools/build_ui.py')
        print('UI bundle matches all source modules.')
    else:
        path.parent.mkdir(exist_ok=True)
        path.write_text(result)
        print('Built dist/MatchaUI.lua')
